In [111]:
import numpy as np

# from tensorflow import keras
#
# from keras.preprocessing.text import Tokenizer

# tokenizer = Tokenizer(char_level=True)

filename = "winnie.txt"

# filename = 'little.txt'


In [112]:
# read the file and covert to lowercase

text = open(filename, 'r').read().lower()

print('total number of characters: ', len(text))





total number of characters:  122781


In [113]:
dictianory= sorted(list(set(text)))
print('total number of unique characters: ', len(dictianory))

total number of unique characters:  52


In [114]:
char_to_int = dict((char, i) for i, char in enumerate(dictianory))

In [115]:
int_to_char = dict((i, char) for i, char in enumerate(dictianory))

In [116]:
int_to_char

{0: '\n',
 1: ' ',
 2: '!',
 3: '"',
 4: "'",
 5: '(',
 6: ')',
 7: '*',
 8: ',',
 9: '-',
 10: '.',
 11: '0',
 12: '1',
 13: '2',
 14: '3',
 15: '4',
 16: '5',
 17: '6',
 18: '7',
 19: '8',
 20: '9',
 21: ':',
 22: ';',
 23: '?',
 24: '_',
 25: 'a',
 26: 'b',
 27: 'c',
 28: 'd',
 29: 'e',
 30: 'f',
 31: 'g',
 32: 'h',
 33: 'i',
 34: 'j',
 35: 'k',
 36: 'l',
 37: 'm',
 38: 'n',
 39: 'o',
 40: 'p',
 41: 'q',
 42: 'r',
 43: 's',
 44: 't',
 45: 'u',
 46: 'v',
 47: 'w',
 48: 'x',
 49: 'y',
 50: 'z',
 51: 'æ'}

In [117]:
char_to_int

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 "'": 4,
 '(': 5,
 ')': 6,
 '*': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '?': 23,
 '_': 24,
 'a': 25,
 'b': 26,
 'c': 27,
 'd': 28,
 'e': 29,
 'f': 30,
 'g': 31,
 'h': 32,
 'i': 33,
 'j': 34,
 'k': 35,
 'l': 36,
 'm': 37,
 'n': 38,
 'o': 39,
 'p': 40,
 'q': 41,
 'r': 42,
 's': 43,
 't': 44,
 'u': 45,
 'v': 46,
 'w': 47,
 'x': 48,
 'y': 49,
 'z': 50,
 'æ': 51}

In [118]:
text_len = len(text)

In [119]:
text_len

122781

In [120]:
x_data = []
y_data = []
seq_length = 12
for i in range(text_len - seq_length - 1):
    data = text[i:i + seq_length]
    label = text[i+1 : i + 1 + seq_length]
#     print("data : " + data + " label : " + label)
    x_data.append([char_to_int[char] for char in data])
    y_data.append([char_to_int[char] for char in label])





In [121]:
a = x_data[0]
b = y_data[0]

In [122]:
[int_to_char[num] for num in a]

['h', 'e', 'r', 'e', ' ', 'i', 's', ' ', 'e', 'd', 'w', 'a']

In [123]:
[int_to_char[num] for num in b]

['e', 'r', 'e', ' ', 'i', 's', ' ', 'e', 'd', 'w', 'a', 'r']

In [124]:
x_data[0]

[32, 29, 42, 29, 1, 33, 43, 1, 29, 28, 47, 25]

In [125]:
len(y_data)

122768

In [126]:
x_data_one_hot = []
y_data_one_hot = []
for i in range(len(x_data)):
    x = x_data[i]
    y = y_data[i]
    one_hots_x = []
    one_hots_y = []
    for j in range(len(x)):

        zeros_x = np.zeros(len(dictianory))
        zeros_y = np.zeros(len(dictianory))

        zeros_y[y[j]] = 1
        zeros_x[x[j]] = 1

        one_hots_x.append(zeros_x)
        one_hots_y.append(zeros_y)
#         print(one_hots_x)

    x_data_one_hot.append(one_hots_x)
    y_data_one_hot.append(one_hots_y)


In [127]:
a = x_data_one_hot[0]
b = y_data_one_hot[0]

In [128]:
a

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]),
 array([0., 1., 0., 0., 0., 0., 

In [129]:
[int_to_char[np.argmax(a[i])] for i in range(len(a))]

['h', 'e', 'r', 'e', ' ', 'i', 's', ' ', 'e', 'd', 'w', 'a']

In [130]:
[int_to_char[np.argmax(b[i])] for i in range(len(b))]

['e', 'r', 'e', ' ', 'i', 's', ' ', 'e', 'd', 'w', 'a', 'r']

In [131]:
x_data_one_hot = np.array(x_data_one_hot)

In [132]:
y_data_one_hot = np.array(y_data_one_hot)

In [133]:
x_data_one_hot.shape

(122768, 12, 52)

In [137]:
class Recurent:
    def __init__(self,input_dim,hidden_step_dim):

        self.input_dim = input_dim
        self.hidden_step_dim = hidden_step_dim
#         self.W_x = np.random.rand(self.input_dim, self.hidden_step_dim) * 0.1
        self.W_x = np.random.uniform(-np.sqrt(1/52),np.sqrt(1/52),(self.input_dim, self.hidden_step_dim))
#         self.W_h = np.random.rand(self.hidden_step_dim, self.hidden_step_dim) * 0.1
        self.W_h = np.random.uniform(-np.sqrt(1/52),np.sqrt(1/52), (self.hidden_step_dim, self.hidden_step_dim))
#         self.W_o = np.random.rand(self.hidden_step_dim,self.input_dim) * 0.1/
        self.W_o = np.random.uniform(-np.sqrt(1/52),np.sqrt(1/52),(self.hidden_step_dim,self.input_dim))
        self.b_o = np.zeros((self.input_dim))
        self.b_h = np.zeros((self.hidden_step_dim))
        self.hidden_units = []
        self.output_units = []


#         self.hidden_units = [((1,hidden_step_dim))]
    def fit(self,X,Y,int_to_char,char_to_int,seq_length, epochs = 1000,lr = 0.01):



        #separating X and Y by time steps

        X_t = np.array([X[:,i,:] for i in range(X.shape[1])])
        Y_t = np.array([Y[:,i,:] for i in range(Y.shape[1])])

        #params for adam
        # b1 = 0.9
        # b2 = 0.999
        # eps = 1e-6
        # first_moments = [0] * 5
        # second_moments = [0] * 5
        r = [0] * 5
        #performing feedforward
        for epoch in range(1,epochs + 1):
            self.hidden_units = [np.zeros((X_t.shape[1],self.hidden_step_dim))]
            self.output_units = []

            for t in range(X_t.shape[0]):
                h_prev = self.hidden_units[-1]
                h_t = np.tanh(X_t[t] @ self.W_x + h_prev @ self.W_h + self.b_h)

                self.hidden_units.append(h_t)

                o_t = h_t @ self.W_o + self.b_o
                softmaxed = np.apply_along_axis(Recurent.softmax, axis =1 , arr = o_t)
                self.output_units.append(softmaxed)

            #computing losses
            self.loss = 0
            for i,output in enumerate(self.output_units):
#                 self.loss+= -1 * (np.sum(Y_t[i] * np.log(output) ))/X_t.shape[1]
#                 self.loss += -1 * (np.sum(np.log(output[Y_t[i] == 1])))
                  self.loss += -np.sum(Y_t[i] * np.log(output))


            print('epoch : {} , loss : {}'.format(epoch,self.loss/X_t.shape[1]))

            #computing gradients
            grads = [0] * 5
            # grads [dW_o,  d_b_o ,  d_W_x,  d_W_h,  d_b_h ]
            for t in reversed(range(len(self.output_units))):

                #t = 4
                grad_flow = self.output_units[t] - Y_t[t]
#                 print(t)
#                 print('----------------')
                d_W_o = self.hidden_units[t + 1].T @ grad_flow
                grads[0] += d_W_o

                d_b_o = np.sum(grad_flow ,axis = 0)
                grads[1] += d_b_o

                grad_flow = grad_flow @ self.W_o.T

                for i in reversed(range(t + 1)):
#                     print(t,i)
                    grad_flow = grad_flow * ( 1 - self.hidden_units[i + 1]**2)
#                     print('self.hidden_units', i)
                    d_W_x = X_t[i].T @  grad_flow
                    d_W_h = self.hidden_units[i].T @ grad_flow
                    d_b_h = np.sum(grad_flow, axis = 0)

                    grads[2] += d_W_x
                    grads[3] += d_W_h
                    grads[4] += d_b_h

                    grad_flow = grad_flow @ self.W_h.T

            grads = [ (delta/X_t.shape[1]).clip(-1,1) for delta in grads]
            self.grads = grads
            if epoch % 99 == 0:
                lr = lr/10

#             #adam
#             first_moments = [b1 * first_moments[i] + ( 1- b1) * grads[i] for i in range(len(grads))]
#             second_moments = [b2 * second_moments[i] + (1 - b2) * grads[i]*grads[i] for i in range(len(grads))]

#             corrected_first = [first_moments[i]/( 1- b1 **epoch) for i in range(len(grads))]
#             corrected_second = [second_moments[i]/(1 - b2**epoch) for i in range(len(grads))]


#             update = [lr * first_moments[i]/(np.sqrt(second_moments[i] + eps)) * grads[i] for i in range(len(grads))]
            #adagrad
            delta = 10 **( -7)
            r = [r[i]  + grads[i] * grads[i] for i in range(len(grads))]
            update = [- (grads[i] * lr)/(delta + np.sqrt(r[i])) for i in range(len(grads)) ]

            #update_params
            # grads [dW_o,  d_b_o ,  d_W_x,  d_W_h,  d_b_h ]
            self.W_o += update[0]
            self.b_o += update[1]
            self.W_x += update[2]
            self.W_h += update[3]
            self.b_h += update[4]
#             print(grads[0])
            self.generate(int_to_char,char_to_int,seq_length)




    def generate(self,int_to_char,char_to_int,seq_length,init_text = 't'):
        text = init_text

        hidden = np.zeros(self.hidden_step_dim)
        for _ in range(50):
#             print(init_text)
            ints = char_to_int[init_text]
            input = np.zeros(len(char_to_int))
            input[ints] = 1

            inputs = np.array(input)

            output = []
            # print(inputs.reshape(-1,1).shape,self.W_x.shape,hidden.reshape(-1,1).shape,self.b_h.reshape(-1,1).shape)
            h_t = np.tanh(inputs.reshape(1,-1) @ self.W_x + hidden.reshape(1,-1) @ self.W_h + self.b_h.reshape(1,-1))
            hidden = h_t

            o_t = h_t @ self.W_o + self.b_o
            softmaxed = Recurent.softmax(o_t)
            arr = np.arange(0,len(char_to_int),1,dtype = 'uint8')
            symb = np.random.choice(a = arr,p = softmaxed.flatten())



            char = int_to_char[symb]

            text += char

            init_text = text[-1]

        print(text)


    @staticmethod
    def softmax(x):
        return(np.exp(x)/np.exp(x).sum())





In [138]:
rnn = Recurent(52,40)

In [ ]:
rnn.fit(x_data_one_hot,y_data_one_hot,int_to_char,char_to_int,seq_length)

epoch : 1 , loss : 47.41879595339236
t.* 3z9v 90pjj3_m4ze5)6or(e_98u1q7w3(9.-a
l x:8c8*(
epoch : 2 , loss : 46.92332880789946
tzvy)(gru!p:*qfod,4*4:j2*apfæjfv3!*os
:yh8uhwp3xt4s
epoch : 3 , loss : 46.30976436975119
tmchyo-c3r3
crg;sbdp25d -vsm4sv)6!p4nl*ui*xælbu:*2y
epoch : 4 , loss : 44.83862877711157
tu"(8tl:2nnlzk8p)d?**l rcse ligujdn0y"re9g6?0
jas(m
epoch : 5 , loss : 41.88365895056688
tdn etnea2nshs:h deeoe  v  oib a.eaoho
yas  t sahxs
epoch : 6 , loss : 39.94717596307442
tpoh1sflnith nr tedeimeejwn"rn4 
nngitf,ett  :40the
epoch : 7 , loss : 39.07540578416165
tegt o
l ifwetdst:tvwaosi5oruv iewh
cr at ute  h? ,
epoch : 8 , loss : 38.651387827907215
t2suaa easwhot8hhr.i ykiaah  6u8h,er ai h" g h "ek 
epoch : 9 , loss : 38.40728566723935
teamdiws,ab_  s nry ylenoe,no tto ttfe s,gld lærhso
epoch : 10 , loss : 38.24353032680312
t8(joab sde hd oom
o  fodswrsheletiloph"6omst,n cir
epoch : 11 , loss : 38.12264747355613
tssyzbans.  lea6ppawbhne
e,lto r _al "  ttab8aajfa*
epoch : 12 , loss 

In [ ]:
#So the model is trying symbol-level text generation 