In [1]:
import numpy as np

from tensorflow import keras

from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(char_level=True)

filename = "winnie.txt"

# filename = 'little.txt'


2023-07-01 09:05:16.911722: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-01 09:05:18.134629: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
# read the file and covert to lowercase

text = open(filename, 'r').read().lower()

print('total number of characters: ', len(text))





total number of characters:  122781


In [3]:
dictianory= sorted(list(set(text)))
print('total number of unique characters: ', len(dictianory))

total number of unique characters:  52


In [4]:
char_to_int = dict((char, i) for i, char in enumerate(dictianory))

In [5]:
int_to_char = dict((i, char) for i, char in enumerate(dictianory))

In [6]:
int_to_char

{0: '\n',
 1: ' ',
 2: '!',
 3: '"',
 4: "'",
 5: '(',
 6: ')',
 7: '*',
 8: ',',
 9: '-',
 10: '.',
 11: '0',
 12: '1',
 13: '2',
 14: '3',
 15: '4',
 16: '5',
 17: '6',
 18: '7',
 19: '8',
 20: '9',
 21: ':',
 22: ';',
 23: '?',
 24: '_',
 25: 'a',
 26: 'b',
 27: 'c',
 28: 'd',
 29: 'e',
 30: 'f',
 31: 'g',
 32: 'h',
 33: 'i',
 34: 'j',
 35: 'k',
 36: 'l',
 37: 'm',
 38: 'n',
 39: 'o',
 40: 'p',
 41: 'q',
 42: 'r',
 43: 's',
 44: 't',
 45: 'u',
 46: 'v',
 47: 'w',
 48: 'x',
 49: 'y',
 50: 'z',
 51: 'æ'}

In [7]:
char_to_int

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 "'": 4,
 '(': 5,
 ')': 6,
 '*': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '?': 23,
 '_': 24,
 'a': 25,
 'b': 26,
 'c': 27,
 'd': 28,
 'e': 29,
 'f': 30,
 'g': 31,
 'h': 32,
 'i': 33,
 'j': 34,
 'k': 35,
 'l': 36,
 'm': 37,
 'n': 38,
 'o': 39,
 'p': 40,
 'q': 41,
 'r': 42,
 's': 43,
 't': 44,
 'u': 45,
 'v': 46,
 'w': 47,
 'x': 48,
 'y': 49,
 'z': 50,
 'æ': 51}

In [8]:
text_len = len(text)

In [9]:
text_len

122781

In [10]:
x_data = []
y_data = []
seq_length = 5
for i in range(text_len - seq_length - 1):
    data = text[i:i + seq_length]
    label = text[i+1 : i + 1 + seq_length]
#     print("data : " + data + " label : " + label)
    x_data.append([char_to_int[char] for char in data])
    y_data.append([char_to_int[char] for char in label])
    
    
    
    

In [11]:
a = x_data[0]
b = y_data[0]

In [12]:
[int_to_char[num] for num in a]

['h', 'e', 'r', 'e', ' ']

In [13]:
[int_to_char[num] for num in b]

['e', 'r', 'e', ' ', 'i']

In [14]:
x_data[0]

[32, 29, 42, 29, 1]

In [15]:
len(y_data)

122775

In [16]:
x_data_one_hot = []
y_data_one_hot = []
for i in range(len(x_data)):
    x = x_data[i]
    y = y_data[i]
    one_hots_x = []
    one_hots_y = []
    for j in range(len(x)):
        
        zeros_x = np.zeros(len(dictianory))
        zeros_y = np.zeros(len(dictianory))
        
        zeros_y[y[j]] = 1
        zeros_x[x[j]] = 1
       
        one_hots_x.append(zeros_x)
        one_hots_y.append(zeros_y)
#         print(one_hots_x)
       
    x_data_one_hot.append(one_hots_x)
    y_data_one_hot.append(one_hots_y)
    

In [17]:
a = x_data_one_hot[0]
b = y_data_one_hot[0]

In [18]:
a

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]),
 array([0., 1., 0., 0., 0., 0., 

In [19]:
[int_to_char[np.argmax(a[i])] for i in range(len(a))]

['h', 'e', 'r', 'e', ' ']

In [20]:
[int_to_char[np.argmax(b[i])] for i in range(len(b))]

['e', 'r', 'e', ' ', 'i']

In [21]:
x_data_one_hot = np.array(x_data_one_hot)

In [22]:
y_data_one_hot = np.array(y_data_one_hot)

In [23]:
x_data_one_hot.shape

(122775, 5, 52)

In [54]:
class Recurent:
    def __init__(self,input_dim,hidden_step_dim):
        
        self.input_dim = input_dim
        self.hidden_step_dim = hidden_step_dim
        self.W_x = np.random.rand(self.input_dim, self.hidden_step_dim) * 0.01
#         self.W_x = np.random.uniform(-np.sqrt(1/52),np.sqrt(1/52),(self.input_dim, self.hidden_step_dim))
        self.W_h = np.random.rand(self.hidden_step_dim, self.hidden_step_dim) * 0.01
#         self.W_h = np.random.uniform(-np.sqrt(1/52),np.sqrt(1/52), (self.hidden_step_dim, self.hidden_step_dim))
        self.W_o = np.random.rand(self.hidden_step_dim,self.input_dim) * 0.01
#         self.W_o = np.random.uniform(-np.sqrt(1/52),np.sqrt(1/52),(self.hidden_step_dim,self.input_dim))
        self.b_o = np.zeros((self.input_dim))
        self.b_h = np.zeros((self.hidden_step_dim))
        self.hidden_units = []
        self.output_units = []
        
        
#         self.hidden_units = [((1,hidden_step_dim))]
    def fit(self,X,Y,int_to_char,char_to_int,seq_length, epochs = 1000,lr = 0.1):
        
        
        
        #separating X and Y by time steps
        
        X_t = np.array([X[:,i,:] for i in range(X.shape[1])])
        Y_t = np.array([Y[:,i,:] for i in range(Y.shape[1])])
        
        #params for adam
        b1 = 0.9
        b2 = 0.999
        eps = 1e-6
        first_moments = [0] * 5
        second_moments = [0] * 5
        #performing feedforward
        for epoch in range(1,epochs + 1): 
            self.hidden_units = [np.zeros((X_t.shape[1],self.hidden_step_dim))]
            self.output_units = []
            
            for t in range(X_t.shape[0]):
                h_prev = self.hidden_units[-1]
                h_t = np.tanh(X_t[t] @ self.W_x + h_prev @ self.W_h + self.b_h)
                self.hidden_units.append(h_t)
                
                o_t = h_t @ self.W_o + self.b_o
                softmaxed = np.apply_along_axis(Recurent.softmax, axis =1 , arr = o_t)
                self.output_units.append(softmaxed)
            
            #computing losses
            self.loss = 0
            for i,output in enumerate(self.output_units):
#                 self.loss+= -1 * (np.sum(Y_t[i] * np.log(output) ))/X_t.shape[1]
                self.loss += -1 * (np.sum(np.log(output[Y_t[i] == 1])))
                
            
            print('epoch : {} , loss : {}'.format(epoch,self.loss/X_t.shape[1]))
            
            #computing gradients
            grads = [0] * 5 
            # grads [dW_o,  d_b_o ,  d_W_x,  d_W_h,  d_b_h ]
            for t in reversed(range(len(self.output_units))):
                
                #t = 4
                grad_flow = self.output_units[t] - Y_t[t]
#                 print(t)
#                 print('----------------')
                d_W_o = self.hidden_units[t + 1].T @ grad_flow
                grads[0] += d_W_o
                
                d_b_o = np.sum(grad_flow ,axis = 0)
                grads[1] += d_b_o
                
                grad_flow = grad_flow @ self.W_o.T
                
                for i in reversed(range(t + 1)):
                    print(t,i)
                    grad_flow = grad_flow * ( 1 - self.hidden_units[i + 1]**2)
                    print('self.hidden_units', i)
                    d_W_x = X_t[i].T @  grad_flow
                    d_W_h = self.hidden_units[i].T @ grad_flow
                    d_b_h = np.sum(grad_flow, axis = 0)
                    
                    grads[2] += d_W_x
                    grads[3] += d_W_h
                    grads[4] += d_b_h
                    
                    grad_flow = grad_flow @ self.W_h.T
                    
            grads = [ (delta/X_t.shape[1]).clip(-1,1) for delta in grads]
            self.grads = grads
            if epoch % 10 == 0:
                lr /= 10
            
            #adam
            first_moments = [b1 * first_moments[i] + ( 1- b1) * grads[i] for i in range(len(grads))]
            second_moments = [b2 * second_moments[i] + (1 - b2) * grads[i]*grads[i] for i in range(len(grads))]
            
            corrected_first = [first_moments[i]/( 1- b1 **epoch) for i in range(len(grads))]
            corrected_second = [second_moments[i]/(1 - b2**epoch) for i in range(len(grads))]
            
            
            update = [lr * first_moments[i]/(np.sqrt(second_moments[i] + eps)) * grads[i] for i in range(len(grads))]
            
            #update_params
            # grads [dW_o,  d_b_o ,  d_W_x,  d_W_h,  d_b_h ]
            self.W_o += update[0]
            self.b_o += update[1]
            self.W_x += update[2]
            self.W_h += update[3]
            self.b_h += update[4]
#             print(grads[0])
            self.generate(int_to_char,char_to_int,seq_length)
        
           
    
    
    def generate(self,int_to_char,char_to_int,seq_length,init_text = 'about'):
        text = init_text
        
        
        for _ in range(50):
#             print(init_text)
            ints = [char_to_int[i] for i in init_text]
            
            inputs = []
            for i in ints:
                zeros = np.zeros(len(char_to_int))
                zeros[i] = 1
                inputs.append(zeros)
            inputs = np.array(inputs)
            hidden = [np.zeros(self.hidden_step_dim)]
            output = []
            for t in range(inputs.shape[0]):
                h_prev = hidden[-1]
                h_t = np.tanh(inputs[t] @ self.W_x + h_prev @ self.W_h + self.b_h)
                hidden.append(h_t)
                
                o_t = h_t @ self.W_o + self.b_o
                softmaxed = Recurent.softmax(o_t)
                output.append(softmaxed)
            symb = np.argmax(output[-1])
            char = int_to_char[symb]
            
            text += char
            
            init_text = text[-seq_length:]
            
        print(text)
            
            
            
            
    
    @staticmethod
    def tanh(x):
        return np.tanh(x)
    @staticmethod
    def d_tanh(x):
        return 1 - np.tanh(x)**2
        
    @staticmethod
    def softmax(x):
        return(np.exp(x)/np.exp(x).sum())
        
        
        
        

In [55]:
rnn = Recurent(52,18)

In [56]:
rnn.fit(x_data_one_hot,y_data_one_hot,int_to_char,char_to_int,seq_length)

epoch : 1 , loss : 19.756220769019226
4 4
self.hidden_units 4
4 3
self.hidden_units 3
4 2
self.hidden_units 2
4 1
self.hidden_units 1
4 0
self.hidden_units 0
3 3
self.hidden_units 3
3 2
self.hidden_units 2
3 1
self.hidden_units 1
3 0
self.hidden_units 0
2 2
self.hidden_units 2
2 1
self.hidden_units 1
2 0
self.hidden_units 0
1 1
self.hidden_units 1
1 0
self.hidden_units 0
0 0
self.hidden_units 0
about                                                  


KeyboardInterrupt: 

In [ ]:
i = 5

In [ ]:
for t in reversed(range(-1,i)):
    for k in reversed(range(t)):
        print(t,k)

In [ ]:
for i in reversed(range(5)):
    for j in reversed(range(i)):
        print(j,i)

In [ ]:
for i in range(5):
    t = 5 - i -1 
    for 

In [ ]:
for i in reversed(range(5)):
    for j in reversed(range(i + 1)):
        print(i,j)